// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to use File Search Tool with a ChatClientAgent.

using Azure.AI.Extensions.OpenAI;
using Azure.AI.Projects;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Assistants;
using OpenAI.Files;
using System.Text;

Console.InputEncoding = Encoding.UTF8;
Console.OutputEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

var endpoint = "https://rg-maf.services.ai.azure.com/api/projects/maf";//Environment.GetEnvironmentVariable("FOUNDRY_PROJECT_ENDPOINT") ?? throw new InvalidOperationException("FOUNDRY_PROJECT_ENDPOINT is not set.");
var deploymentName = "gpt-4o";// Environment.GetEnvironmentVariable("FOUNDRY_MODEL") ?? "gpt-5.4-mini";

const string AgentInstructions = "你是一个乐于助人的助手，可以搜索上传的文件以回答问题。";


AIProjectClient aiProjectClient = new(new Uri(endpoint), new DefaultAzureCredential());

ProjectOpenAIClient projectOpenAIClient = aiProjectClient.GetProjectOpenAIClient();

ProjectFilesClient projectFilesClient = projectOpenAIClient.GetProjectFilesClient();

ProjectVectorStoresClient projectVectorStoresClient = projectOpenAIClient.GetProjectVectorStoresClient();

var searchFilePath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName() + "_lookup.txt");

File.WriteAllText(
    path: searchFilePath,
    contents: """
        员工目录：
        - 桂兵兵，40岁，软件架构师，软件开发部
        - 张三，35岁，销售经理，销售部
        - 李四，42岁，人力资源总监，人力资源部
        - 王五，31岁，客户支持主管，支持部
        """
);

Console.WriteLine($"上传文件: {searchFilePath}");

OpenAIFile uploadedFile = projectFilesClient.UploadFile(
    filePath: searchFilePath,
    purpose: FileUploadPurpose.Assistants
);
Console.WriteLine($"已上传文件, 文件 ID: {uploadedFile.Id}");


var vectorStoreResult = await projectVectorStoresClient.CreateVectorStoreAsync(
    options: new() { FileIds = { uploadedFile.Id }, Name = "EmployeeDirectory_VectorStore" }
);
string vectorStoreId = vectorStoreResult.Value.Id;
Console.WriteLine($"已创建向量存储, 向量存储 ID: {vectorStoreId}");

// 创建一个 AIAgent 并使用 HostedFileSearchTool。
AIAgent agent = aiProjectClient.AsAIAgent(deploymentName,
    instructions: AgentInstructions,
    name: "FileSearchAgent-RAPI",
    tools: [new HostedFileSearchTool() { Inputs = [new HostedVectorStoreContent(vectorStoreId)] }]);

// 运行代理以搜索文件内容。
Console.WriteLine("\n--- 运行文件搜索代理 ---");
AgentResponse response = await agent.RunAsync("谁是最年轻的员工？");
Console.WriteLine($"响应: {response}");

// Getting any file citation annotations generated by the tool
foreach (AIAnnotation annotation in response.Messages.SelectMany(m => m.Contents).SelectMany(c => c.Annotations ?? []))
{
#pragma warning disable OPENAI001 
    if (annotation.RawRepresentation is TextAnnotationUpdate citationAnnotation)
    {
        Console.WriteLine($$"""
            文件引用:

              文件 ID: {{citationAnnotation.OutputFileId}}
              要替换的文本: {{citationAnnotation.TextToReplace}}
            """);
    }
#pragma warning restore OPENAI001 
}

// 清理文件资源。
Console.WriteLine("\n--- 清理 ---");
await projectVectorStoresClient.DeleteVectorStoreAsync(vectorStoreId);
await projectFilesClient.DeleteFileAsync(uploadedFile.Id);
File.Delete(searchFilePath);
Console.WriteLine("清理完成。");