// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to use Code Interpreter Tool with AIProjectClient.AsAIAgent(...).

using Azure.AI.Projects;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Files;
using OpenAI.Responses;
using System.Text;


Console.InputEncoding = Encoding.UTF8;
Console.OutputEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

const string AgentInstructions = "你是一个乐于助人的助手。能够使用Python编写和执行代码。";
const string AgentName = "CoderAgent-RAPI";


AIProjectClient aiProjectClient = new(new Uri("https://rg-maf.services.ai.azure.com/api/projects/maf"), new DefaultAzureCredential());

OpenAIFileClient fileClient = aiProjectClient
    .GetProjectOpenAIClient()
    .GetOpenAIFileClient();

OpenAIFile uploadedFile = (await fileClient.UploadFileAsync(
filePath: Path.Combine(Directory.GetCurrentDirectory(),"data","sales_zh.csv"),purpose: FileUploadPurpose.Assistants)).Value;


AIAgent agent = aiProjectClient
    .GetProjectOpenAIClient()
    .GetProjectResponsesClient()
    .AsAIAgent(
        model: "gpt-4o",
        instructions: AgentInstructions,
        name: AgentName,
        tools: [new HostedCodeInterpreterTool() { Inputs = [new HostedFileContent(uploadedFile.Id)] }]);

AgentResponse response = await agent.RunAsync($"帮我使用Python脚本统计 {uploadedFile.Id} 文件下不同区域的销售总数,并输出结果");


Console.WriteLine(response.Text);

List<AIContent> responseContents = response.Messages
    .SelectMany(message => message.Contents)
    .ToList();

// Display every Python script generated by Code Interpreter.
IEnumerable<DataContent> codeInputs = responseContents
    .OfType<CodeInterpreterToolCallContent>()
    .Where(toolCall => toolCall.Inputs is not null)
    .SelectMany(toolCall => toolCall.Inputs!)
    .OfType<DataContent>()
    .Where(input => input.HasTopLevelMediaType("text"));

foreach (DataContent codeInput in codeInputs)
{
    Console.WriteLine($$"""
        Generated script ({{codeInput.MediaType}}):
        {{Encoding.UTF8.GetString(codeInput.Data.Span)}}
        """);
}

await fileClient.DeleteFileAsync(uploadedFile.Id);

